
import type { Phase } from './types';
import { Brain, Search, Edit3, Share2, BarChart2, Zap, CheckCircle, Lightbulb, Download } from 'lucide-react';

export const phasesData: Phase[] = [
  {
    id: 'phase1',
    headline: 'Unternehmen Finden',
    imageSrc: 'https://the-decoder.com/wp-content/uploads/2025/03/deepersearch_grok.png',
    imageAlt: 'Screenshot of Grok AI interface',
    dataAiHint: 'AI search',
    description: 'Als erstes gibt du den Prompt an Grok um nach Unternehmen zu suchen die neue neue Webseite gebrauchen könnten. Schau dir die Vorschläge selber an und und beurteile ob da ein guter Kandidat dabei ist. Schau dir die Beispiel Screenshots die bei der Auswahl helfen könnten.',
    toolUrl: 'https://grok.com/',
    toolName: 'Grok',
    toolIcon: Brain,
    promptFileName: 'phase1_ideation.txt',
  },
  {
    id: 'phase2',
    headline: 'Informationen vom Unternehmen rausziehen',
    imageSrc: 'https://the-decoder.com/wp-content/uploads/2025/03/deepersearch_grok.png',
    imageAlt: 'Screenshot of Grok AI interface with Deepsearch feature',
    dataAiHint: 'AI deepsearch',
    description: 'kopiere den prompt und ein neues Chat Fenster von Grok und \u2028kopiere einer der  URL/Webseite Addresse raus  z.b. www.UnternehmenABC.de und setzte sie ein wo steht PLATZHALTER\u2028\nverwende hier DEEPSEARCH',
    toolUrl: 'https://grok.com/',
    toolName: 'Grok (Deepsearch)',
    toolIcon: Brain,
    promptFileName: 'phase2_research.txt',
  },
  {
    id: 'phase3',
    headline: 'Prompt für Website Genererierung erstellen',
    imageSrc: 'https://ai-rockstars.de/wp-content/uploads/2025/03/google-ai-studio.png',
    imageAlt: 'Screenshot of Google AI Studio interface',
    dataAiHint: 'AI studio website',
    description: 'Kopiere den nächsten Prompt C und hänge am Ende Das an was beim letzten Prompt rauskam, füge auch das extra Dokument an.',
    toolUrl: 'https://aistudio.google.com/u/1/prompts/new_chat',
    toolName: 'Google AI Studio',
    toolIcon: Lightbulb,
    promptFileName: 'phase3_creation.txt',
    extraAction: {
      text: 'Download extra Dokument',
      url: 'https://drive.google.com/file/d/1GhGJoQI7j0yB1V_z-M7aa5nOcAeALYvl/view?usp=sharing',
      icon: Download,
    },
  },
  {
    id: 'phase4',
    headline: 'Webseite verbessern',
    imageSrc: 'https://mintlify.s3.us-west-1.amazonaws.com/lovable-f9060f1e/lovable-editor-v2.png',
    imageAlt: 'Lovable editor interface with chat window',
    dataAiHint: 'website editor',
    description: 'Kopiere diesen prompt in das chat fenster links ein, drücke erst auf "Chat" und klicke dann enter.\nWarte und wenn es fertig ist. drücke entweder auf Implement the Plan, oder schreibe "Implement the Plan" in den Chat',
    toolUrl: 'https://lovable.dev/',
    toolName: 'Lovable',
    toolIcon: Edit3,
    promptFileName: 'phase4_refinement.txt',
  },
  {
    id: 'phase5',
    headline: 'Phase 5: Visuals & Design',
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Palette and brush, indicating visual design',
    dataAiHint: 'design palette',
    description: 'Create or select visuals and design elements. AI image generators can create custom graphics, or AI-powered design tools can suggest layouts and branding.',
    toolUrl: 'https://www.midjourney.com',
    toolName: 'Midjourney',
    toolIcon: BarChart2, // Using BarChart2 as a generic "tool" icon
    promptFileName: 'phase5_visuals.txt',
  },
  {
    id: 'phase6',
    headline: 'Phase 6: Automation & Optimization',
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Gears turning, symbolizing automation',
    dataAiHint: 'automation gears',
    description: 'Automate repetitive tasks and optimize processes. AI can help with scheduling, data entry, customer support chatbots, or optimizing workflows for efficiency.',
    toolUrl: 'https://zapier.com',
    toolName: 'Zapier',
    toolIcon: Zap,
    promptFileName: 'phase6_automation.txt',
  },
  {
    id: 'phase7',
    headline: 'Phase 7: Finalization & Deployment',
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Rocket launching, signifying deployment',
    dataAiHint: 'launch rocket',
    description: 'Finalize all components and prepare for deployment or launch. This may involve final checks, packaging, and distributing the completed work.',
    toolUrl: '#', // Placeholder for a general deployment tool or checklist
    toolName: 'Final Check',
    toolIcon: CheckCircle,
    promptFileName: 'phase7_finalization.txt',
  },
];
